package com.example.ui

object Localization {
    private val en = mapOf(
        "app_title" to "Backlog Workspace Hub",
        "auth_welcome_signup" to "Create Workspace Account",
        "auth_welcome_login" to "Backlog Workspace Hub",
        "auth_desc_signup" to "Sign up to collaborate and manage sprint plans",
        "auth_desc_login" to "Enter your email credentials to proceed to task board",
        "label_display_name" to "Display Name",
        "label_email_address" to "Email Address",
        "label_password" to "Password",
        "placeholder_display_name" to "e.g., Miler Cenizario",
        "placeholder_email" to "name@example.com",
        "placeholder_password" to "At least 6 characters",
        "btn_register" to "Register Account",
        "btn_login" to "Sign In",
        "switch_to_login" to "Already have an account? Sign In",
        "switch_to_signup" to "New to the platform? Create account",
        
        "tab_home" to "Home",
        "tab_tasks" to "Tasks",
        "tab_chat" to "Collaborate",
        "tab_settings" to "Settings",
        
        "home_title" to "Active Sprint Progress",
        "home_subtitle" to "Workspace Overview",
        "home_completed_sprints" to "Completed Sprints",
        "home_active_sprint_health" to "Active Sprint Health",
        "home_progress_desc" to "Progress tracker reflecting task completions",
        "home_priority_backlog" to "High Priority Backlog Items",
        "home_no_priority_tasks" to "No high priority tasks pending!",
        "home_priority" to "Priority",
        "home_pending" to "Pending",
        "home_click_stats" to "Click to view full distribution analytics & stats",
        "home_team_title" to "Sprint Team Members",
        "home_team_subtitle" to "Active collaborators on sprint backlog",
        "home_team_manage" to "Manage Team",
        "home_btn_stats" to "View Workspace Metrics",
        
        "title_settings" to "Backlog Settings",
        "settings_role" to "Role: Core Sprint Stakeholder",
        "settings_btn_logout" to "Log Out",
        "settings_section_lang" to "Application Language",
        "settings_lang_desc" to "Choose your preferred interface language:",
        
        "tasks_search_placeholder" to "Search backlog item...",
        "tasks_all_categories" to "All Columns",
        
        "chat_title" to "Collaborative Chat",
        "chat_comment_placeholder" to "Comment on backlog item...",
        "chat_user_role" to "Workspace Collaborator",
        
        "dialog_card_edit" to "Edit Backlog Item",
        "dialog_card_add" to "Add Backlog Item",
        "field_title" to "Task Title",
        "field_description" to "Task Description",
        "field_priority" to "Task Priority",
        "field_column" to "Sprint Column",
        "btn_save" to "Save",
        "btn_delete" to "Delete",
        "btn_cancel" to "Cancel",
        "btn_add" to "Add Task",
        
        "metrics_distribution" to "Task Distribution",
        "metrics_by_column" to "Cards per Column",
        "metrics_high_priority_count" to "High Priority Backlog Count",
        "metrics_total_count" to "Total Backlog Cards",
        "btn_close" to "Close",
        
        "roster_title" to "Collaborator Directory",
        "roster_desc" to "Registered workspace team members sync updates in real-time.",
        "roster_role_lead" to "Lead Architect",
        "roster_role_pm" to "Product Manager",
        "roster_role_qa" to "Senior QA",
        
        // Image exports
        "btn_export_image" to "Export as Image",
        "btn_export_report" to "Export Sprint Report",
        "export_dialog_title" to "Export Successful",
        "export_dialog_desc" to "A high-fidelity PNG image has been generated and exported!",
        "export_dialog_status" to "Saved to Device's Local Gallery",
        "export_btn_share" to "Share PNG Image",
        "export_preview_label" to "Visual Image Preview:",
        "export_toast" to "Sprint report image generated and exported successfully!",
        
        "active_backlog" to "ACTIVE BACKLOG",
        "backlog_clear" to "BACKLOG CLEAR",
        "on_track" to "ON TRACK",
        "accomplished" to "ACCOMPLISHED",
        "high_priority_pending" to "{count} high priority items pending",
        "ready_for_work" to "Ready to accept work!",
        "btn_details" to "Details",
        "priority_backlog_tasks" to "Priority Backlog Tasks",
        "zero_high_priority" to "Zero high priority items pending!",
        "board_synced" to "Backlog workspace is fully synchronized",
        "timeline_tracker" to "Timeline Tracker",
        "roadmap_active" to "4 roadmap lines active",
        "collaboration_team" to "Collaboration Team",
        "members_assigned" to "8 members assigned",
        "export_banner_title" to "Sprint Report Snapshot",
        "export_banner_desc" to "Generate a beautiful visual PNG infographic of your sprint backlog distribution, progress metrics, and team performance, ready to share with stakeholders.",
        "tab_settings_title" to "Backlog Settings",
        "tab_settings_language_title" to "Application Language",
        "tab_settings_language_desc" to "Choose your preferred interface language:",
        "lbl_role" to "Role",
        "btn_logout" to "Log Out",
        "admin_actions" to "Administrative Actions",
        "data_mgmt" to "Data Management Options",
        "data_mgmt_desc" to "These database operations interact directly with Room local persistence.",
        "btn_seed" to "Seed Data",
        "btn_clear" to "Clear Board",
        "edit_item" to "Edit Backlog Feature",
        "All fields are required" to "All fields are required",
        "Invalid email format" to "Invalid email format",
        "Password must be at least 6 characters" to "Password must be at least 6 characters",
        "Account with this email already exists" to "Account with this email already exists",
        "Incorrect email or password" to "Incorrect email or password"
    )

    private val es = mapOf(
        "app_title" to "Centro de Backlog de Trabajo",
        "auth_welcome_signup" to "Crear Cuenta de Espacio de Trabajo",
        "auth_welcome_login" to "Centro de Backlog de Trabajo",
        "auth_desc_signup" to "Regístrese para colaborar y administrar planes de sprint",
        "auth_desc_login" to "Ingrese sus credenciales para continuar al tablero de tareas",
        "label_display_name" to "Nombre a Mostrar",
        "label_email_address" to "Correo Electrónico",
        "label_password" to "Contraseña",
        "placeholder_display_name" to "ej., Miler Cenizario",
        "placeholder_email" to "nombre@ejemplo.com",
        "placeholder_password" to "Al menos 6 caracteres",
        "btn_register" to "Registrar Cuenta",
        "btn_login" to "Iniciar Sesión",
        "switch_to_login" to "¿Ya tienes una cuenta? Iniciar Sesión",
        "switch_to_signup" to "¿Nuevo en la plataforma? Crear cuenta",
        
        "tab_home" to "Inicio",
        "tab_tasks" to "Tareas",
        "tab_chat" to "Colaborar",
        "tab_settings" to "Ajustes",
        
        "home_title" to "Progreso del Sprint Activo",
        "home_subtitle" to "Vista General del Espacio de Trabajo",
        "home_completed_sprints" to "Sprints Completados",
        "home_active_sprint_health" to "Salud del Sprint Activo",
        "home_progress_desc" to "Rastreador de progreso que refleja tareas completas",
        "home_priority_backlog" to "Elementos de Alta Prioridad",
        "home_no_priority_tasks" to "¡No hay tareas de alta prioridad pendientes!",
        "home_priority" to "Prioridad",
        "home_pending" to "Pendientes",
        "home_click_stats" to "Clic para ver análisis y estadísticas de distribución",
        "home_team_title" to "Equipo del Sprint",
        "home_team_subtitle" to "Colaboradores activos en el backlog del sprint",
        "home_team_manage" to "Gestionar Equipo",
        "home_btn_stats" to "Ver Métricas del Espacio",
        
        "title_settings" to "Ajustes de Backlog",
        "settings_role" to "Rol: Colaborador Principal del Sprint",
        "settings_btn_logout" to "Cerrar Sesión",
        "settings_section_lang" to "Idioma de la Aplicación",
        "settings_lang_desc" to "Selecciona tu idioma preferido para la interfaz:",
        
        "tasks_search_placeholder" to "Buscar elemento de backlog...",
        "tasks_all_categories" to "Todas las Columnas",
        
        "chat_title" to "Chat Colaborativo",
        "chat_comment_placeholder" to "Comentar sobre tarea del backlog...",
        "chat_user_role" to "Colaborador del Espacio",
        
        "dialog_card_edit" to "Editar Elemento de Backlog",
        "dialog_card_add" to "Agregar Elemento de Backlog",
        "field_title" to "Título de la Tarea",
        "field_description" to "Descripción de la Tarea",
        "field_priority" to "Prioridad de la Tarea",
        "field_column" to "Columna de Sprint",
        "btn_save" to "Guardar",
        "btn_delete" to "Eliminar",
        "btn_cancel" to "Cancelar",
        "btn_add" to "Añadir Tarea",
        
        "metrics_distribution" to "Distribución de Tareas",
        "metrics_by_column" to "Tarjetas por Columna",
        "metrics_high_priority_count" to "Conteo de Alta Prioridad",
        "metrics_total_count" to "Total de Tarjetas de Backlog",
        "btn_close" to "Cerrar",
        
        "roster_title" to "Directorio de Colaboradores",
        "roster_desc" to "Los miembros del equipo sincronizan actualizaciones en tiempo real.",
        "roster_role_lead" to "Arquitecto Principal",
        "roster_role_pm" to "Gerente de Producto",
        "roster_role_qa" to "QA Senior",
        
        // Image exports
        "btn_export_image" to "Exportar como Imagen",
        "btn_export_report" to "Exportar Reporte del Sprint",
        "export_dialog_title" to "Exportación Exitosa",
        "export_dialog_desc" to "¡Se ha generado y exportado la imagen PNG de alta fidelidad!",
        "export_dialog_status" to "Guardado en la Galería del Dispositivo",
        "export_btn_share" to "Compartir Imagen PNG",
        "export_preview_label" to "Vista Previa de Imagen:",
        "export_toast" to "¡La imagen del reporte se generó y exportó con éxito!",
        
        "active_backlog" to "BACKLOG ACTIVO",
        "backlog_clear" to "BACKLOG COMPLETO",
        "on_track" to "EN CURSO",
        "accomplished" to "COMPLETADO",
        "high_priority_pending" to "{count} elementos de alta prioridad pendientes",
        "ready_for_work" to "¡Listo para aceptar trabajo!",
        "btn_details" to "Detalles",
        "priority_backlog_tasks" to "Tareas de Backlog Prioritarias",
        "zero_high_priority" to "¡Cero elementos de alta prioridad pendientes!",
        "board_synced" to "Espacio de trabajo del backlog completamente sincronizado",
        "timeline_tracker" to "Seguimiento de Tiempo",
        "roadmap_active" to "4 líneas de hoja de ruta activas",
        "collaboration_team" to "Equipo de Colaboración",
        "members_assigned" to "8 miembros asignados",
        "export_banner_title" to "Captura del Reporte del Sprint",
        "export_banner_desc" to "Genera una hermosa infografía visual en PNG de la distribución del backlog, métricas de progreso y rendimiento del equipo, lista para compartir con stakeholders.",
        "tab_settings_title" to "Ajustes de Backlog",
        "tab_settings_language_title" to "Idioma de la Aplicación",
        "tab_settings_language_desc" to "Selecciona tu idioma preferido para la interfaz:",
        "lbl_role" to "Rol",
        "btn_logout" to "Cerrar Sesión",
        "admin_actions" to "Acciones Administrativas",
        "data_mgmt" to "Opciones de Gestión de Datos",
        "data_mgmt_desc" to "Estas operaciones de base de datos interactúan directamente con la persistencia local de Room.",
        "btn_seed" to "Generar Datos",
        "btn_clear" to "Limpiar Tablero",
        "edit_item" to "Editar Característica del Backlog",
        "All fields are required" to "Todos los campos son obligatorios",
        "Invalid email format" to "Formato de correo electrónico no válido",
        "Password must be at least 6 characters" to "La contraseña debe tener al menos 6 caracteres",
        "Account with this email already exists" to "Ya existe una cuenta con este correo electrónico",
        "Incorrect email or password" to "Correo electrónico o contraseña incorrectos"
    )

    private val pt = mapOf(
        "app_title" to "Centro de Backlog de Trabalho",
        "auth_welcome_signup" to "Criar Conta de Espaço de Trabalho",
        "auth_welcome_login" to "Centro de Backlog de Trabalho",
        "auth_desc_signup" to "Inscreva-se para colaborar e gerenciar planos de sprint",
        "auth_desc_login" to "Insira suas credenciais para continuar para o quadro de tarefas",
        "label_display_name" to "Nome de Exibição",
        "label_email_address" to "Endereço de E-mail",
        "label_password" to "Senha",
        "placeholder_display_name" to "ex., Miler Cenizario",
        "placeholder_email" to "nome@exemplo.com",
        "placeholder_password" to "Pelo menos 6 caracteres",
        "btn_register" to "Registrar Conta",
        "btn_login" to "Entrar",
        "switch_to_login" to "Já tem uma conta? Entrar",
        "switch_to_signup" to "Novo na plataforma? Criar conta",
        
        "tab_home" to "Início",
        "tab_tasks" to "Tarefas",
        "tab_chat" to "Colaborar",
        "tab_settings" to "Ajustes",
        
        "home_title" to "Progresso do Sprint Ativo",
        "home_subtitle" to "Visão Geral do Espaço de Trabalho",
        "home_completed_sprints" to "Sprints Concluídos",
        "home_active_sprint_health" to "Saúde do Sprint Ativo",
        "home_progress_desc" to "Rastreador de progresso correspondente a tarefas concluídas",
        "home_priority_backlog" to "Itens de Alta Prioridade",
        "home_no_priority_tasks" to "Sem tarefas de alta prioridade pendentes!",
        "home_priority" to "Prioridade",
        "home_pending" to "Pendentes",
        "home_click_stats" to "Clique para ver análises e estatísticas de distribuição",
        "home_team_title" to "Equipe do Sprint",
        "home_team_subtitle" to "Membros ativos colaborando no backlog do sprint",
        "home_team_manage" to "Gerenciar Equipe",
        "home_btn_stats" to "Ver Métricas",
        
        "title_settings" to "Configurações do Backlog",
        "settings_role" to "Função: Colaborador Principal do Sprint",
        "settings_btn_logout" to "Sair",
        "settings_section_lang" to "Idioma do Aplicativo",
        "settings_lang_desc" to "Escolha seu idioma de preferência para a interface:",
        
        "tasks_search_placeholder" to "Buscar item do backlog...",
        "tasks_all_categories" to "Todas as Colunas",
        
        "chat_title" to "Chat de Colaboração",
        "chat_comment_placeholder" to "Comentar sobre item do backlog...",
        "chat_user_role" to "Colaborador do Espaço",
        
        "dialog_card_edit" to "Editar Item do Backlog",
        "dialog_card_add" to "Adicionar Item ao Backlog",
        "field_title" to "Título da Tarefa",
        "field_description" to "Descrição da Tarefa",
        "field_priority" to "Prioridade da Tarefa",
        "field_column" to "Coluna do Sprint",
        "btn_save" to "Salvar",
        "btn_delete" to "Excluir",
        "btn_cancel" to "Cancelar",
        "btn_add" to "Adicionar Tarefa",
        
        "metrics_distribution" to "Distribuição das Tarefas",
        "metrics_by_column" to "Cartões por Coluna",
        "metrics_high_priority_count" to "Cartões de Alta Prioridade",
        "metrics_total_count" to "Total do Backlog",
        "btn_close" to "Fechar",
        
        "roster_title" to "Diretório de Colaboradores",
        "roster_desc" to "Membros sincronizam atualizações em tempo real.",
        "roster_role_lead" to "Arquiteto Principal",
        "roster_role_pm" to "Gerente de Produto",
        "roster_role_qa" to "QA Sênior",
        
        // Image exports
        "btn_export_image" to "Exportar como Imagem",
        "btn_export_report" to "Exportar Relatório do Sprint",
        "export_dialog_title" to "Exportação Concluída",
        "export_dialog_desc" to "A imagem PNG de alta fidelidade foi gerada e exportada!",
        "export_dialog_status" to "Salvo com sucesso na Galeria",
        "export_btn_share" to "Compartilhar Imagem PNG",
        "export_preview_label" to "Visualização da Imagem:",
        "export_toast" to "Imagem do relatório gerada e exportada com sucesso!",
        
        "active_backlog" to "BACKLOG ATIVO",
        "backlog_clear" to "BACKLOG LIMPO",
        "on_track" to "NO CAMINHO",
        "accomplished" to "CONCLUÍDO",
        "high_priority_pending" to "{count} itens de alta prioridade pendentes",
        "ready_for_work" to "Pronto para aceitar trabalho!",
        "btn_details" to "Detalhes",
        "priority_backlog_tasks" to "Tarefas de Backlog Prioritárias",
        "zero_high_priority" to "Zero itens de alta prioridade pendentes!",
        "board_synced" to "Espaço de trabalho do backlog totalmente sincronizado",
        "timeline_tracker" to "Rastreador de Linha do Tempo",
        "roadmap_active" to "4 linhas de planejamento ativas",
        "collaboration_team" to "Equipe de Colaboração",
        "members_assigned" to "8 membros atribuídos",
        "export_banner_title" to "Captura do Relatório do Sprint",
        "export_banner_desc" to "Gere um belo infográfico em PNG da distribuição do seu backlog, métricas de progresso e desempenho da equipe, pronto para compartilhar com as partes interessadas.",
        "tab_settings_title" to "Configurações do Backlog",
        "tab_settings_language_title" to "Idioma do Aplicativo",
        "tab_settings_language_desc" to "Escolha seu idioma de preferência para a interface:",
        "lbl_role" to "Função",
        "btn_logout" to "Sair",
        "admin_actions" to "Ações Administrativas",
        "data_mgmt" to "Gerenciamento de Dados",
        "data_mgmt_desc" to "Estas operações de banco de dados interagem diretamente com a persistência local do Room.",
        "btn_seed" to "Semear Dados",
        "btn_clear" to "Limpar Quadro",
        "edit_item" to "Editar Funcionalidade",
        "All fields are required" to "Todos os campos são obrigatórios",
        "Invalid email format" to "Formato de e-mail inválido",
        "Password must be at least 6 characters" to "A senha deve ter pelo menos 6 caracteres",
        "Account with this email already exists" to "Já existe uma conta com este e-mail",
        "Incorrect email or password" to "E-mail ou senha incorretos"
    )

    fun get(key: String, lang: String): String {
        val map = when (lang) {
            "es" -> es
            "pt" -> pt
            else -> en
        }
        return map[key] ?: en[key] ?: key
    }
}
